---
Mappings:
    RegionMap:
        us-east-1:
            "64x86": "ami-033b95fb8079dc481"
            "64arm": "ami-0f7691f59fd7c47af"
Resources:
    MyInstance:
        Type: AWS::EC2::Instance
        Properties:
            AvailabilityZone: us-east-1a
            ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", 64x86]
            InstanceType: t2.micro